// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	"bytes"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//info
type ServerInfo struct {
	ServerId             int64    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ServerType           int32    `protobuf:"varint,2,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerVersion        int32    `protobuf:"varint,3,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	State                int64    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	ServerName           string   `protobuf:"bytes,5,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetServerId() int64 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ServerInfo) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ServerInfo) GetServerVersion() int32 {
	if m != nil {
		return m.ServerVersion
	}
	return 0
}

func (m *ServerInfo) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ServerInfo) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type UserInfo struct {
	UId                  int64    `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	UsersId              []int64  `protobuf:"varint,2,rep,packed,name=UsersId,proto3" json:"UsersId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUId() int64 {
	if m != nil {
		return m.UId
	}
	return 0
}

func (m *UserInfo) GetUsersId() []int64 {
	if m != nil {
		return m.UsersId
	}
	return nil
}

//msg
type NewConnect struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewConnect) Reset()         { *m = NewConnect{} }
func (m *NewConnect) String() string { return proto.CompactTextString(m) }
func (*NewConnect) ProtoMessage()    {}
func (*NewConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *NewConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewConnect.Unmarshal(m, b)
}
func (m *NewConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewConnect.Marshal(b, m, deterministic)
}
func (m *NewConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewConnect.Merge(m, src)
}
func (m *NewConnect) XXX_Size() int {
	return xxx_messageInfo_NewConnect.Size(m)
}
func (m *NewConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_NewConnect.DiscardUnknown(m)
}

var xxx_messageInfo_NewConnect proto.InternalMessageInfo

func (m *NewConnect) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DelConnect struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelConnect) Reset()         { *m = DelConnect{} }
func (m *DelConnect) String() string { return proto.CompactTextString(m) }
func (*DelConnect) ProtoMessage()    {}
func (*DelConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *DelConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelConnect.Unmarshal(m, b)
}
func (m *DelConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelConnect.Marshal(b, m, deterministic)
}
func (m *DelConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelConnect.Merge(m, src)
}
func (m *DelConnect) XXX_Size() int {
	return xxx_messageInfo_DelConnect.Size(m)
}
func (m *DelConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_DelConnect.DiscardUnknown(m)
}

var xxx_messageInfo_DelConnect proto.InternalMessageInfo

func (m *DelConnect) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ServerDelConnect struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerDelConnect) Reset()         { *m = ServerDelConnect{} }
func (m *ServerDelConnect) String() string { return proto.CompactTextString(m) }
func (*ServerDelConnect) ProtoMessage()    {}
func (*ServerDelConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *ServerDelConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerDelConnect.Unmarshal(m, b)
}
func (m *ServerDelConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerDelConnect.Marshal(b, m, deterministic)
}
func (m *ServerDelConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerDelConnect.Merge(m, src)
}
func (m *ServerDelConnect) XXX_Size() int {
	return xxx_messageInfo_ServerDelConnect.Size(m)
}
func (m *ServerDelConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerDelConnect.DiscardUnknown(m)
}

var xxx_messageInfo_ServerDelConnect proto.InternalMessageInfo

func (m *ServerDelConnect) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ServerTick struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	State                int64    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTick) Reset()         { *m = ServerTick{} }
func (m *ServerTick) String() string { return proto.CompactTextString(m) }
func (*ServerTick) ProtoMessage()    {}
func (*ServerTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *ServerTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTick.Unmarshal(m, b)
}
func (m *ServerTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTick.Marshal(b, m, deterministic)
}
func (m *ServerTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTick.Merge(m, src)
}
func (m *ServerTick) XXX_Size() int {
	return xxx_messageInfo_ServerTick.Size(m)
}
func (m *ServerTick) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTick.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTick proto.InternalMessageInfo

func (m *ServerTick) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ServerTick) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

type ServerLoginRQ struct {
	Serverinfo           *ServerInfo `protobuf:"bytes,1,opt,name=serverinfo,proto3" json:"serverinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerLoginRQ) Reset()         { *m = ServerLoginRQ{} }
func (m *ServerLoginRQ) String() string { return proto.CompactTextString(m) }
func (*ServerLoginRQ) ProtoMessage()    {}
func (*ServerLoginRQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *ServerLoginRQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerLoginRQ.Unmarshal(m, b)
}
func (m *ServerLoginRQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerLoginRQ.Marshal(b, m, deterministic)
}
func (m *ServerLoginRQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerLoginRQ.Merge(m, src)
}
func (m *ServerLoginRQ) XXX_Size() int {
	return xxx_messageInfo_ServerLoginRQ.Size(m)
}
func (m *ServerLoginRQ) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerLoginRQ.DiscardUnknown(m)
}

var xxx_messageInfo_ServerLoginRQ proto.InternalMessageInfo

func (m *ServerLoginRQ) GetServerinfo() *ServerInfo {
	if m != nil {
		return m.Serverinfo
	}
	return nil
}

type ServerLoginRS struct {
	Result               int32       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Serverinfo           *ServerInfo `protobuf:"bytes,2,opt,name=serverinfo,proto3" json:"serverinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerLoginRS) Reset()         { *m = ServerLoginRS{} }
func (m *ServerLoginRS) String() string { return proto.CompactTextString(m) }
func (*ServerLoginRS) ProtoMessage()    {}
func (*ServerLoginRS) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *ServerLoginRS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerLoginRS.Unmarshal(m, b)
}
func (m *ServerLoginRS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerLoginRS.Marshal(b, m, deterministic)
}
func (m *ServerLoginRS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerLoginRS.Merge(m, src)
}
func (m *ServerLoginRS) XXX_Size() int {
	return xxx_messageInfo_ServerLoginRS.Size(m)
}
func (m *ServerLoginRS) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerLoginRS.DiscardUnknown(m)
}

var xxx_messageInfo_ServerLoginRS proto.InternalMessageInfo

func (m *ServerLoginRS) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ServerLoginRS) GetServerinfo() *ServerInfo {
	if m != nil {
		return m.Serverinfo
	}
	return nil
}

type ServerRegister struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Fuid                 []uint32 `protobuf:"varint,2,rep,packed,name=fuid,proto3" json:"fuid,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerRegister) Reset()         { *m = ServerRegister{} }
func (m *ServerRegister) String() string { return proto.CompactTextString(m) }
func (*ServerRegister) ProtoMessage()    {}
func (*ServerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *ServerRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerRegister.Unmarshal(m, b)
}
func (m *ServerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerRegister.Marshal(b, m, deterministic)
}
func (m *ServerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerRegister.Merge(m, src)
}
func (m *ServerRegister) XXX_Size() int {
	return xxx_messageInfo_ServerRegister.Size(m)
}
func (m *ServerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ServerRegister proto.InternalMessageInfo

func (m *ServerRegister) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ServerRegister) GetFuid() []uint32 {
	if m != nil {
		return m.Fuid
	}
	return nil
}

func (m *ServerRegister) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ServerDelFunc struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Fuid                 []uint32 `protobuf:"varint,2,rep,packed,name=fuid,proto3" json:"fuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerDelFunc) Reset()         { *m = ServerDelFunc{} }
func (m *ServerDelFunc) String() string { return proto.CompactTextString(m) }
func (*ServerDelFunc) ProtoMessage()    {}
func (*ServerDelFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *ServerDelFunc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerDelFunc.Unmarshal(m, b)
}
func (m *ServerDelFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerDelFunc.Marshal(b, m, deterministic)
}
func (m *ServerDelFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerDelFunc.Merge(m, src)
}
func (m *ServerDelFunc) XXX_Size() int {
	return xxx_messageInfo_ServerDelFunc.Size(m)
}
func (m *ServerDelFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerDelFunc.DiscardUnknown(m)
}

var xxx_messageInfo_ServerDelFunc proto.InternalMessageInfo

func (m *ServerDelFunc) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ServerDelFunc) GetFuid() []uint32 {
	if m != nil {
		return m.Fuid
	}
	return nil
}

type ServerCall struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	FromMId              int64     `protobuf:"varint,2,opt,name=fromMId,proto3" json:"fromMId,omitempty"`
	ToMId                int64     `protobuf:"varint,3,opt,name=toMId,proto3" json:"toMId,omitempty"`
	FUId                 uint32    `protobuf:"varint,4,opt,name=fUId,proto3" json:"fUId,omitempty"`
	CUId                 string    `protobuf:"bytes,5,opt,name=cUId,proto3" json:"cUId,omitempty"`
	Msginfo              []byte    `protobuf:"bytes,6,opt,name=msginfo,proto3" json:"msginfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerCall) Reset()         { *m = ServerCall{} }
func (m *ServerCall) String() string { return proto.CompactTextString(m) }
func (*ServerCall) ProtoMessage()    {}
func (*ServerCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *ServerCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCall.Unmarshal(m, b)
}
func (m *ServerCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCall.Marshal(b, m, deterministic)
}
func (m *ServerCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCall.Merge(m, src)
}
func (m *ServerCall) XXX_Size() int {
	return xxx_messageInfo_ServerCall.Size(m)
}
func (m *ServerCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCall.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCall proto.InternalMessageInfo

func (m *ServerCall) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ServerCall) GetFromMId() int64 {
	if m != nil {
		return m.FromMId
	}
	return 0
}

func (m *ServerCall) GetToMId() int64 {
	if m != nil {
		return m.ToMId
	}
	return 0
}

func (m *ServerCall) GetFUId() uint32 {
	if m != nil {
		return m.FUId
	}
	return 0
}

func (m *ServerCall) GetCUId() string {
	if m != nil {
		return m.CUId
	}
	return ""
}

func (m *ServerCall) GetMsginfo() []byte {
	if m != nil {
		return m.Msginfo
	}
	return nil
}

type ServerCallBack struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	FromMId              int64     `protobuf:"varint,2,opt,name=fromMId,proto3" json:"fromMId,omitempty"`
	ToMId                int64     `protobuf:"varint,3,opt,name=toMId,proto3" json:"toMId,omitempty"`
	CUId                 string    `protobuf:"bytes,4,opt,name=cUId,proto3" json:"cUId,omitempty"`
	Msginfo              []byte    `protobuf:"bytes,5,opt,name=msginfo,proto3" json:"msginfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerCallBack) Reset()         { *m = ServerCallBack{} }
func (m *ServerCallBack) String() string { return proto.CompactTextString(m) }
func (*ServerCallBack) ProtoMessage()    {}
func (*ServerCallBack) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *ServerCallBack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCallBack.Unmarshal(m, b)
}
func (m *ServerCallBack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCallBack.Marshal(b, m, deterministic)
}
func (m *ServerCallBack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCallBack.Merge(m, src)
}
func (m *ServerCallBack) XXX_Size() int {
	return xxx_messageInfo_ServerCallBack.Size(m)
}
func (m *ServerCallBack) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCallBack.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCallBack proto.InternalMessageInfo

func (m *ServerCallBack) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ServerCallBack) GetFromMId() int64 {
	if m != nil {
		return m.FromMId
	}
	return 0
}

func (m *ServerCallBack) GetToMId() int64 {
	if m != nil {
		return m.ToMId
	}
	return 0
}

func (m *ServerCallBack) GetCUId() string {
	if m != nil {
		return m.CUId
	}
	return ""
}

func (m *ServerCallBack) GetMsginfo() []byte {
	if m != nil {
		return m.Msginfo
	}
	return nil
}

type DBServerRQ struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Msgid                uint32   `protobuf:"varint,2,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Sql                  string   `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	Key                  []string `protobuf:"bytes,4,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBServerRQ) Reset()         { *m = DBServerRQ{} }
func (m *DBServerRQ) String() string { return proto.CompactTextString(m) }
func (*DBServerRQ) ProtoMessage()    {}
func (*DBServerRQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *DBServerRQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBServerRQ.Unmarshal(m, b)
}
func (m *DBServerRQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBServerRQ.Marshal(b, m, deterministic)
}
func (m *DBServerRQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBServerRQ.Merge(m, src)
}
func (m *DBServerRQ) XXX_Size() int {
	return xxx_messageInfo_DBServerRQ.Size(m)
}
func (m *DBServerRQ) XXX_DiscardUnknown() {
	xxx_messageInfo_DBServerRQ.DiscardUnknown(m)
}

var xxx_messageInfo_DBServerRQ proto.InternalMessageInfo

func (m *DBServerRQ) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DBServerRQ) GetMsgid() uint32 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *DBServerRQ) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *DBServerRQ) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

type DBServerRS struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBServerRS) Reset()         { *m = DBServerRS{} }
func (m *DBServerRS) String() string { return proto.CompactTextString(m) }
func (*DBServerRS) ProtoMessage()    {}
func (*DBServerRS) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *DBServerRS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBServerRS.Unmarshal(m, b)
}
func (m *DBServerRS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBServerRS.Marshal(b, m, deterministic)
}
func (m *DBServerRS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBServerRS.Merge(m, src)
}
func (m *DBServerRS) XXX_Size() int {
	return xxx_messageInfo_DBServerRS.Size(m)
}
func (m *DBServerRS) XXX_DiscardUnknown() {
	xxx_messageInfo_DBServerRS.DiscardUnknown(m)
}

var xxx_messageInfo_DBServerRS proto.InternalMessageInfo

func (m *DBServerRS) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//DB
type DataTableConfig struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_Update           map[string]interface{} `json:"-"`
	XXX_Key              map[string]interface{} `json:"-"`
	XXX_Add              map[string]interface{} `json:"-"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DataTableConfig) Reset()         { *m = DataTableConfig{} }
func (m *DataTableConfig) String() string { return proto.CompactTextString(m) }
func (*DataTableConfig) ProtoMessage()    {}
func (*DataTableConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *DataTableConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTableConfig.Unmarshal(m, b)
}
func (m *DataTableConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTableConfig.Marshal(b, m, deterministic)
}
func (m *DataTableConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTableConfig.Merge(m, src)
}
func (m *DataTableConfig) XXX_Size() int {
	return xxx_messageInfo_DataTableConfig.Size(m)
}
func (m *DataTableConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTableConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataTableConfig proto.InternalMessageInfo

func (m *DataTableConfig) DBDel() string {
	var buff bytes.Buffer
	buff.WriteString("DELETE FROM ")
	buff.WriteString("DataTableConfig")
	buff.WriteString(" WHERE ")
	i := 0
	for k, v := range m.XXX_Update {
		if i > 0 {
			buff.WriteString(" AND ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		i += 1
	}
	return buff.String()
}
func (m *DataTableConfig) DBInsert() string {
	var buff bytes.Buffer
	buff.WriteString("INSERT INTO ")
	buff.WriteString("DataTableConfig")
	buff.WriteString("( ")
	i := 0
	var key bytes.Buffer
	var value bytes.Buffer
	for k, v := range m.XXX_Update {
		if i > 0 {
			key.WriteString(", ")
			value.WriteString(", ")
		}
		key.WriteString(k)
		d := fmt.Sprint(v)
		value.WriteString(d)
		i += 1
	}
	buff.WriteString(key.String())
	buff.WriteString(" ) VALUES ( ")
	buff.WriteString(value.String())
	buff.WriteString(" )")
	return buff.String()
}
func (m *DataTableConfig) DBUpdate() string {
	var buff bytes.Buffer
	buff.WriteString("UPDATE ")
	buff.WriteString("DataTableConfig")
	buff.WriteString(" SET ")
	i := 0
	for k, v := range m.XXX_Update {
		if i > 0 {
			buff.WriteString(", ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		i += 1
	}
	buff.WriteString(" WHERE ")
	i = 0
	for k, v := range m.XXX_Key {
		if i > 0 {
			buff.WriteString(" AND ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		i += 1
	}
	return buff.String()
}
func (m *DataTableConfig) DBSelect() (s string, ks []string) {
	var buff bytes.Buffer
	buff.WriteString("SELECT ")
	i := 0
	if len(m.XXX_Update) == 0 {
		ks = make([]string, 2)
		ks[0] = "Name"
		if i > 0 {
			buff.WriteString(", ")
		}
		buff.WriteString("Name")
		i += 1
		ks[1] = "Data"
		if i > 0 {
			buff.WriteString(", ")
		}
		buff.WriteString("Data")
		i += 1
	} else {
		ks = make([]string, len(m.XXX_Update))
		j := 0
		for k, _ := range m.XXX_Update {
			if i > 0 {
				buff.WriteString(", ")
			}
			buff.WriteString(k)
			ks[j] = k
			j += 1
			i += 1
		}
	}
	buff.WriteString(" FROM ")
	buff.WriteString("DataTableConfig")
	i = 0
	for k, v := range m.XXX_Key {
		if i == 0 {
			buff.WriteString(" WHERE ")
		}
		if i > 0 {
			buff.WriteString(" AND ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		i += 1
	}
	s = buff.String()
	return
}
func (m *DataTableConfig) GetFieldID(ks []string) (p []interface{}) {
	if nil == m.XXX_Add {
		m.XXX_Add = make(map[string]interface{})
	}
	m.XXX_Add["Name"] = &m.Name
	m.XXX_Add["Data"] = &m.Data
	p = make([]interface{}, len(ks))
	j := 0
	for _, v := range ks {
		if d, ok := m.XXX_Add[v]; ok && nil != d {
			p[j] = d
			j += 1
		}
	}
	return
}
func (m *DataTableConfig) RedisSet(key interface{}) (table string, data []interface{}) {
	table = "DataTableConfig" + "_" + fmt.Sprint(key)
	data = make([]interface{}, 2*len(m.XXX_Update))
	j := 0
	for k, v := range m.XXX_Update {
		data[j] = k
		data[j+1] = v
		j += 2
	}
	return
}
func (m *DataTableConfig) RedisGet(key interface{}) (table string, data []interface{}) {
	table = "DataTableConfig" + "_" + fmt.Sprint(key)
	if len(m.XXX_Update) == 0 {
		data = make([]interface{}, 2)
		data[0] = "Name"
		data[1] = "Data"
	} else {
		data = make([]interface{}, len(m.XXX_Update))
		j := 0
		for k, _ := range m.XXX_Update {
			data[j] = k
			j += 1
		}
	}
	return
}
func (m *DataTableConfig) RedisDel(key interface{}) (table string, data []interface{}) {
	table = "DataTableConfig" + "_" + fmt.Sprint(key)
	data = make([]interface{}, len(m.XXX_Update))
	j := 0
	for k, _ := range m.XXX_Update {
		data[j] = k
		j += 1
	}
	return
}
func (m *DataTableConfig) DoUpdate() (sql, table string, data []interface{}) {
	var buff bytes.Buffer
	buff.WriteString("UPDATE ")
	buff.WriteString("DataTableConfig")
	buff.WriteString(" SET ")
	i := 0
	j := 0
	data = make([]interface{}, 2*len(m.XXX_Update))
	for k, v := range m.XXX_Update {
		if i > 0 {
			buff.WriteString(", ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		i += 1
		data[j] = k
		data[j+1] = v
		j += 2
		delete(m.XXX_Update, k)
	}
	buff.WriteString(" WHERE ")
	i = 0
	for k, v := range m.XXX_Key {
		if i > 0 {
			buff.WriteString(" AND ")
		}
		buff.WriteString(k)
		d := fmt.Sprint(v)
		buff.WriteString(" = ")
		buff.WriteString(d)
		table = "DataTableConfig" + "_" + d
		i += 1
	}
	sql = buff.String()
	return
}

func (m *DataTableConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTableConfig) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DataTableConfig) SetName(data string) {
	if m != nil {
		m.Name = data
		if nil == m.XXX_Update {
			m.XXX_Update = make(map[string]interface{})
		}
		data = strconv.Quote(data)
		m.XXX_Update["Name"] = data
	}
}

func (m *DataTableConfig) SetKeyName(data string) {
	if m != nil {
		if nil == m.XXX_Key {
			m.XXX_Key = make(map[string]interface{})
		}
		data = strconv.Quote(data)
		m.XXX_Key["Name"] = data
	}
}

func (m *DataTableConfig) SetData(data string) {
	if m != nil {
		m.Data = data
		if nil == m.XXX_Update {
			m.XXX_Update = make(map[string]interface{})
		}
		data = strconv.Quote(data)
		m.XXX_Update["Data"] = data
	}
}

func (m *DataTableConfig) SetKeyData(data string) {
	if m != nil {
		if nil == m.XXX_Key {
			m.XXX_Key = make(map[string]interface{})
		}
		data = strconv.Quote(data)
		m.XXX_Key["Data"] = data
	}
}

type ArrayTableConfig struct {
	Data                 []*DataTableConfig `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArrayTableConfig) Reset()         { *m = ArrayTableConfig{} }
func (m *ArrayTableConfig) String() string { return proto.CompactTextString(m) }
func (*ArrayTableConfig) ProtoMessage()    {}
func (*ArrayTableConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *ArrayTableConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayTableConfig.Unmarshal(m, b)
}
func (m *ArrayTableConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayTableConfig.Marshal(b, m, deterministic)
}
func (m *ArrayTableConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayTableConfig.Merge(m, src)
}
func (m *ArrayTableConfig) XXX_Size() int {
	return xxx_messageInfo_ArrayTableConfig.Size(m)
}
func (m *ArrayTableConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayTableConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayTableConfig proto.InternalMessageInfo

func (m *ArrayTableConfig) GetData() []*DataTableConfig {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerInfo)(nil), "proto.ServerInfo")
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*NewConnect)(nil), "proto.NewConnect")
	proto.RegisterType((*DelConnect)(nil), "proto.DelConnect")
	proto.RegisterType((*ServerDelConnect)(nil), "proto.ServerDelConnect")
	proto.RegisterType((*ServerTick)(nil), "proto.ServerTick")
	proto.RegisterType((*ServerLoginRQ)(nil), "proto.ServerLoginRQ")
	proto.RegisterType((*ServerLoginRS)(nil), "proto.ServerLoginRS")
	proto.RegisterType((*ServerRegister)(nil), "proto.ServerRegister")
	proto.RegisterType((*ServerDelFunc)(nil), "proto.ServerDelFunc")
	proto.RegisterType((*ServerCall)(nil), "proto.ServerCall")
	proto.RegisterType((*ServerCallBack)(nil), "proto.ServerCallBack")
	proto.RegisterType((*DBServerRQ)(nil), "proto.DBServerRQ")
	proto.RegisterType((*DBServerRS)(nil), "proto.DBServerRS")
	proto.RegisterType((*DataTableConfig)(nil), "proto.DataTableConfig")
	proto.RegisterType((*ArrayTableConfig)(nil), "proto.ArrayTableConfig")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x38, 0x34, 0x53, 0xd2, 0x86, 0x15, 0xaa, 0x2c, 0x84, 0x90, 0xb5, 0xf4, 0x60,
	0x71, 0xa8, 0x44, 0x11, 0x95, 0xb8, 0x20, 0x91, 0x44, 0x48, 0x45, 0x50, 0xa9, 0xdb, 0x84, 0x43,
	0x6f, 0x5b, 0x67, 0x13, 0x59, 0x71, 0xec, 0xe2, 0xdd, 0x80, 0xf2, 0x3b, 0xf8, 0x09, 0xf0, 0x43,
	0xd1, 0xcc, 0x7a, 0x1d, 0xa7, 0xa2, 0xa8, 0x17, 0x4e, 0x9e, 0x8f, 0xdd, 0x37, 0x6f, 0xdf, 0x1b,
	0x43, 0x6f, 0xa5, 0x17, 0x27, 0xb7, 0x55, 0x69, 0x4a, 0x16, 0xd2, 0x87, 0xff, 0xf6, 0x00, 0xae,
	0x54, 0xf5, 0x5d, 0x55, 0xe7, 0xc5, 0xbc, 0x64, 0xcf, 0x60, 0x4f, 0xdb, 0x6c, 0x16, 0x79, 0xb1,
	0x97, 0x04, 0xa2, 0xc9, 0xd9, 0x0b, 0x00, 0x1b, 0x4f, 0x36, 0xb7, 0x2a, 0xf2, 0x63, 0x2f, 0x09,
	0x45, 0xab, 0xc2, 0x8e, 0xa1, 0x6f, 0xb3, 0xaf, 0xaa, 0xd2, 0x59, 0x59, 0x44, 0x01, 0x1d, 0xd9,
	0x2d, 0xb2, 0xa7, 0x10, 0x6a, 0x23, 0x8d, 0x8a, 0x3a, 0x04, 0x6f, 0x93, 0x2d, 0xf6, 0x85, 0x5c,
	0xa9, 0x28, 0x8c, 0xbd, 0xa4, 0x27, 0x5a, 0x15, 0x7e, 0x06, 0x7b, 0x53, 0x5d, 0x73, 0x1c, 0x40,
	0x30, 0x6d, 0xe8, 0x61, 0xc8, 0x22, 0x78, 0x84, 0x5d, 0x7d, 0x3e, 0x8b, 0xfc, 0x38, 0x48, 0x02,
	0xe1, 0x52, 0xfe, 0x1c, 0xe0, 0x42, 0xfd, 0x18, 0x95, 0x45, 0xa1, 0x52, 0xc3, 0x0e, 0xc0, 0xcf,
	0xdc, 0x45, 0x3f, 0xa3, 0xee, 0x58, 0xe5, 0xf7, 0x75, 0x39, 0x0c, 0xac, 0x32, 0xff, 0x38, 0x73,
	0xe6, 0xd4, 0x9b, 0x64, 0xe9, 0x92, 0x31, 0xe8, 0x98, 0x6c, 0xa5, 0xea, 0x3e, 0xc5, 0xdb, 0xf7,
	0xfa, 0xad, 0xf7, 0xf2, 0x21, 0xf4, 0xed, 0xbd, 0xcf, 0xe5, 0x22, 0x2b, 0xc4, 0x25, 0x7b, 0xed,
	0x04, 0xc8, 0x8a, 0x79, 0x49, 0x00, 0xfb, 0xa7, 0x4f, 0xac, 0x55, 0x27, 0x5b, 0x7f, 0x44, 0xeb,
	0x10, 0xbf, 0xde, 0xc5, 0xb8, 0x62, 0x47, 0xd0, 0xad, 0x94, 0x5e, 0xe7, 0x86, 0xee, 0x87, 0xa2,
	0xce, 0xee, 0x60, 0xfb, 0x0f, 0xc1, 0xfe, 0x04, 0x07, 0xb6, 0x23, 0xd4, 0x22, 0xd3, 0x46, 0x55,
	0xa8, 0xfa, 0xba, 0x79, 0x3a, 0x86, 0xf8, 0xda, 0x39, 0x96, 0x50, 0xf2, 0xbe, 0xa0, 0x98, 0x14,
	0xc0, 0xed, 0xb0, 0xd6, 0x53, 0xcc, 0xdf, 0x3a, 0x9e, 0x63, 0x95, 0x7f, 0x5c, 0x17, 0xe9, 0xc3,
	0xa0, 0xf8, 0xaf, 0x66, 0x33, 0x47, 0x32, 0xcf, 0xd9, 0x4b, 0xe8, 0xa0, 0xa9, 0xb5, 0x34, 0x87,
	0x35, 0x7d, 0xb7, 0x14, 0x82, 0x9a, 0xb8, 0x08, 0xf3, 0xaa, 0x5c, 0x7d, 0xa1, 0x45, 0x40, 0x74,
	0x97, 0xa2, 0x0d, 0xa6, 0xc4, 0x7a, 0x60, 0x6d, 0xa0, 0x84, 0xe6, 0xe2, 0x2e, 0xe1, 0x2e, 0xe2,
	0xdc, 0xa9, 0xad, 0xa5, 0x58, 0xb3, 0x4b, 0x48, 0x31, 0xe2, 0xae, 0xf4, 0x82, 0xe4, 0xeb, 0xc6,
	0x5e, 0xf2, 0x58, 0xb8, 0x94, 0xff, 0xf4, 0x9c, 0x52, 0xc8, 0x72, 0x28, 0xd3, 0xe5, 0x7f, 0x63,
	0x9a, 0x3a, 0xa6, 0x7f, 0x61, 0x15, 0xee, 0xb2, 0xba, 0x06, 0x18, 0x0f, 0x6b, 0x03, 0x2f, 0x1b,
	0x53, 0xbc, 0xad, 0x29, 0x38, 0x05, 0x0f, 0xdb, 0xe9, 0x7d, 0x61, 0x13, 0x74, 0x46, 0x7f, 0xcb,
	0x69, 0x72, 0x4f, 0x60, 0x88, 0x95, 0xa5, 0xda, 0x44, 0x9d, 0x38, 0xc0, 0xca, 0x52, 0x6d, 0xf8,
	0x71, 0x0b, 0xfb, 0xde, 0x9d, 0xe3, 0xef, 0xe0, 0x70, 0x2c, 0x8d, 0x9c, 0xc8, 0x9b, 0x5c, 0x8d,
	0xca, 0x62, 0x9e, 0x2d, 0x90, 0x46, 0x21, 0xeb, 0xbf, 0xa3, 0x27, 0x28, 0xc6, 0xda, 0x4c, 0x1a,
	0x49, 0x2c, 0x7a, 0x82, 0x62, 0xfe, 0x1e, 0x06, 0x1f, 0xaa, 0x4a, 0x6e, 0xda, 0x77, 0x5f, 0xd5,
	0xe7, 0xbc, 0x38, 0x48, 0xf6, 0x4f, 0x8f, 0x6a, 0x4d, 0xef, 0x4c, 0xb0, 0xf7, 0x6f, 0xba, 0xd4,
	0x7c, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x48, 0x6f, 0xc4, 0xed, 0x04, 0x00, 0x00,
}
